import { promises as fs } from 'node:fs';
import path from 'node:path';
import { loadConfig } from '../config-loader.js';
import { getString, type ParsedArgs } from '../args.js';
import { log } from '../logger.js';
import { runGenerateFromOpenApi } from './generate-from-openapi.js';

/**
 * `mcify generate` dispatches to subcommands:
 *
 *   - bare       → emit an SDK stub from the local `mcify.config.ts`
 *   - from-openapi <spec> [--spec name=url]... → generate Zod-typed tools
 *
 * The bare form will eventually emit a fully-typed client SDK from the
 * server's Zod schemas. For V1 it ships a minimal stub that lists the tools
 * so consumers can at least import a `McifyTool` union.
 */
export const runGenerate = async (args: ParsedArgs): Promise<void> => {
  const subcommand = args.positional[1];
  if (subcommand === 'from-openapi') {
    await runGenerateFromOpenApi(args);
    return;
  }
  if (subcommand && subcommand !== '') {
    log.error(`Unknown generate subcommand: "${subcommand}"`);
    log.hint('Available: from-openapi');
    log.hint('Or run `mcify generate` with no subcommand to emit an SDK stub.');
    process.exit(1);
  }

  const configFlag = getString(args, 'config');
  const configPath = path.resolve(process.cwd(), configFlag ?? 'mcify.config.ts');
  const outFlag = getString(args, 'out');
  const outPath = path.resolve(process.cwd(), outFlag ?? 'mcify-client.ts');

  let config;
  try {
    config = await loadConfig(configPath);
  } catch (e) {
    log.error(e instanceof Error ? e.message : String(e));
    process.exit(1);
  }

  const tools = config.tools ?? [];
  const resources = config.resources ?? [];
  const prompts = config.prompts ?? [];

  const toolNamesUnion = tools.length === 0 ? 'never' : tools.map((t) => `'${t.name}'`).join(' | ');
  const resourceUrisUnion =
    resources.length === 0 ? 'never' : resources.map((r) => `'${r.uri}'`).join(' | ');
  const promptNamesUnion =
    prompts.length === 0 ? 'never' : prompts.map((p) => `'${p.name}'`).join(' | ');

  const lines = [
    '// Generated by `mcify generate`. Do not edit by hand.',
    '// Re-run after changing tools, resources, or prompts.',
    '',
    `// Server: ${config.name}@${config.version}`,
    `// Tools: ${tools.length}, Resources: ${resources.length}, Prompts: ${prompts.length}`,
    '',
    `export type McifyTool = ${toolNamesUnion};`,
    `export type McifyResourceUri = ${resourceUrisUnion};`,
    `export type McifyPrompt = ${promptNamesUnion};`,
    '',
    'export const mcifyServer = {',
    `  name: ${JSON.stringify(config.name)},`,
    `  version: ${JSON.stringify(config.version)},`,
    `  tools: [${tools.map((t) => JSON.stringify(t.name)).join(', ')}] as const,`,
    `  resources: [${resources.map((r) => JSON.stringify(r.uri)).join(', ')}] as const,`,
    `  prompts: [${prompts.map((p) => JSON.stringify(p.name)).join(', ')}] as const,`,
    '};',
    '',
    '// Note: full Zod-derived input/output types arrive in a later release.',
    '',
  ];

  await fs.writeFile(outPath, lines.join('\n'), 'utf-8');
  const rel = path.relative(process.cwd(), outPath) || outPath;
  log.success(`wrote ${rel}`);
  log.hint(`${tools.length} tools, ${resources.length} resources, ${prompts.length} prompts`);
};
