import { promises as fs } from 'node:fs';
import path from 'node:path';
import { loadConfig } from '../config-loader.js';
import { buildEdgeBundle } from './bundle.js';
import { exec, isCommandAvailable } from '../utils/exec.js';
import { fileExists } from '../utils/fs.js';
import { getString, type ParsedArgs } from '../args.js';
import { log } from '../logger.js';

const DEFAULT_COMPATIBILITY_DATE = '2026-01-01';

const generateWranglerToml = (opts: {
  name: string;
  workerPath: string;
  compatibilityDate: string;
}): string =>
  [
    `# Generated by \`mcify deploy cloudflare\`. Edit and re-run to redeploy.`,
    `name = "${opts.name}"`,
    `main = "${opts.workerPath}"`,
    `compatibility_date = "${opts.compatibilityDate}"`,
    `compatibility_flags = ["nodejs_compat"]`,
    ``,
    `# Add your secrets via \`wrangler secret put MCIFY_AUTH_TOKEN\` etc.`,
    `# Or declare bindings here:`,
    `# [vars]`,
    `# MCIFY_AUTH_TOKEN = "..."  # avoid for production secrets — use \`wrangler secret\``,
    ``,
  ].join('\n');

export const runDeployCloudflare = async (args: ParsedArgs): Promise<void> => {
  const configFlag = getString(args, 'config');
  const configPath = path.resolve(process.cwd(), configFlag ?? 'mcify.config.ts');
  const outDir = path.resolve(process.cwd(), getString(args, 'out') ?? 'dist/cloudflare');
  const projectNameFlag = getString(args, 'project-name');
  const accountIdFlag = getString(args, 'account-id');
  const compatibilityDate = getString(args, 'compatibility-date') ?? DEFAULT_COMPATIBILITY_DATE;
  const dryRun = args.flags['dry-run'] === true;

  if (!(await fileExists(configPath))) {
    log.error(`Config not found: ${configPath}`);
    log.hint('Run `mcify init` to scaffold a starter project.');
    process.exit(1);
  }

  log.info('loading config…');
  const config = await loadConfig(configPath);
  const name = projectNameFlag ?? config.name;
  log.hint(`server: ${config.name}@${config.version} → worker name: ${name}`);

  log.info('bundling for Cloudflare Workers…');
  const workerPath = await buildEdgeBundle({
    configPath,
    outDir,
    target: 'workers',
  });
  const stat = await fs.stat(workerPath);
  log.success(`bundle ready (${(stat.size / 1024).toFixed(1)} KB)`);

  // Workers paid plan caps at 10 MB; free tier at 1 MB. We surface a hint
  // before the user hits Cloudflare's error.
  if (stat.size > 10 * 1024 * 1024) {
    log.error(
      'bundle is larger than 10 MB — Cloudflare Workers will reject it. Reduce dependencies or move to a Node target.',
    );
    process.exit(1);
  } else if (stat.size > 1024 * 1024) {
    log.warn(
      'bundle is larger than 1 MB — only the Workers paid plan accepts it. Free tier deploys will fail.',
    );
  }

  const wranglerTomlPath = path.join(outDir, 'wrangler.toml');
  await fs.writeFile(
    wranglerTomlPath,
    generateWranglerToml({
      name,
      workerPath: path.relative(outDir, workerPath).replaceAll('\\', '/'),
      compatibilityDate,
    }),
    'utf-8',
  );
  log.hint(`wrangler.toml → ${path.relative(process.cwd(), wranglerTomlPath)}`);

  if (dryRun) {
    log.info('--dry-run: skipping wrangler deploy');
    log.hint(
      `Run manually: \`pnpm dlx wrangler deploy --config ${path.relative(process.cwd(), wranglerTomlPath)}\``,
    );
    return;
  }

  // We use `npx wrangler` so the user doesn't need a global install.
  // pnpm/npm/yarn all support `dlx`/`exec` style for this. Sticking with
  // `npx` because it's universal across package managers.
  if (!(await isCommandAvailable('npx'))) {
    log.error('npx is required to invoke wrangler. Make sure Node.js is on PATH.');
    process.exit(1);
  }

  log.info('deploying with wrangler…');
  const wranglerArgs = ['wrangler', 'deploy', '--config', wranglerTomlPath];
  if (accountIdFlag) {
    wranglerArgs.push('--account-id', accountIdFlag);
  }

  const result = await exec('npx', wranglerArgs, { stdio: 'inherit' });
  if (result.exitCode !== 0) {
    log.error(`wrangler deploy exited with code ${result.exitCode}`);
    log.hint(
      'Common fixes: run `npx wrangler login`, set CLOUDFLARE_API_TOKEN, or pass --account-id <id>.',
    );
    process.exit(result.exitCode);
  }
  log.success(`deployed to Cloudflare Workers as "${name}"`);
};
