import { promises as fs } from 'node:fs';
import path from 'node:path';
import { buildServer } from '../commands/build.js';
import { exec, isCommandAvailable } from '../utils/exec.js';
import { fileExists } from '../utils/fs.js';
import { getString, type ParsedArgs } from '../args.js';
import { log } from '../logger.js';

const DOCKERFILE_NAME = 'Dockerfile.mcify';

const generateDockerfile = (opts: { entryFile: string; port: number }): string =>
  [
    `# Generated by \`mcify deploy docker\`. Edit and re-build to customize.`,
    `# Multi-stage build: small final image, no source files leaked.`,
    ``,
    `FROM node:20-alpine AS deps`,
    `WORKDIR /app`,
    `COPY package.json package-lock.json* pnpm-lock.yaml* yarn.lock* ./`,
    `# Install only production dependencies. We support npm/pnpm/yarn lockfiles.`,
    `RUN if [ -f pnpm-lock.yaml ]; then \\`,
    `      corepack enable pnpm && pnpm install --prod --frozen-lockfile; \\`,
    `    elif [ -f yarn.lock ]; then \\`,
    `      corepack enable yarn && yarn install --production --frozen-lockfile; \\`,
    `    else \\`,
    `      npm ci --omit=dev; \\`,
    `    fi`,
    ``,
    `FROM node:20-alpine`,
    `WORKDIR /app`,
    `# Run as a non-root user — Node base image ships \`node\` (uid 1000).`,
    `USER node`,
    `COPY --chown=node:node --from=deps /app/node_modules ./node_modules`,
    `COPY --chown=node:node ${opts.entryFile} ./${opts.entryFile}`,
    `COPY --chown=node:node package.json ./package.json`,
    ``,
    `ENV NODE_ENV=production`,
    `ENV PORT=${opts.port}`,
    `EXPOSE ${opts.port}`,
    ``,
    `CMD ["node", "${opts.entryFile}"]`,
    ``,
  ].join('\n');

export const runDeployDocker = async (args: ParsedArgs): Promise<void> => {
  const configFlag = getString(args, 'config');
  const configPath = path.resolve(process.cwd(), configFlag ?? 'mcify.config.ts');
  const tag = getString(args, 'tag') ?? 'mcify-server:latest';
  const platform = getString(args, 'platform');
  const push = args.flags['push'] === true;
  const dryRun = args.flags['dry-run'] === true;
  const portFlag = getString(args, 'port');
  const port = portFlag ? Number.parseInt(portFlag, 10) : 8888;

  if (!(await fileExists(configPath))) {
    log.error(`Config not found: ${configPath}`);
    log.hint('Run `mcify init` to scaffold a starter project.');
    process.exit(1);
  }

  log.info('building Node bundle for the image…');
  const outDir = path.resolve(process.cwd(), 'dist');
  const result = await buildServer({
    configPath,
    outDir,
    target: 'node',
    bundleDeps: false,
  });
  const entryRel = path.relative(process.cwd(), result.outFile).replaceAll('\\', '/');
  log.success(`bundle: ${entryRel} (${result.durationMs}ms)`);

  // Write Dockerfile.mcify next to package.json. Don't overwrite a manual
  // Dockerfile with the same name — the user might have customized it.
  const dockerfilePath = path.resolve(process.cwd(), DOCKERFILE_NAME);
  if (await fileExists(dockerfilePath)) {
    log.hint(`${DOCKERFILE_NAME} → already exists, leaving as-is`);
  } else {
    await fs.writeFile(dockerfilePath, generateDockerfile({ entryFile: entryRel, port }), 'utf-8');
    log.hint(`${DOCKERFILE_NAME} → generated`);
  }

  if (dryRun) {
    log.info('--dry-run: skipping `docker build`');
    log.hint(
      `Run manually: \`docker build -f ${DOCKERFILE_NAME} -t ${tag}${platform ? ` --platform ${platform}` : ''} .\``,
    );
    return;
  }

  if (!(await isCommandAvailable('docker'))) {
    log.error('docker is not on PATH. Install Docker Desktop or the Docker Engine.');
    log.hint('https://docs.docker.com/get-docker/');
    process.exit(1);
  }

  const buildArgs = ['build', '-f', DOCKERFILE_NAME, '-t', tag];
  if (platform) {
    buildArgs.push('--platform', platform);
  }
  buildArgs.push('.');

  log.info(`docker build -t ${tag}${platform ? ` --platform ${platform}` : ''}`);
  const buildResult = await exec('docker', buildArgs, { stdio: 'inherit' });
  if (buildResult.exitCode !== 0) {
    log.error(`docker build exited with code ${buildResult.exitCode}`);
    process.exit(buildResult.exitCode);
  }
  log.success(`built ${tag}`);

  if (push) {
    log.info(`docker push ${tag}`);
    const pushResult = await exec('docker', ['push', tag], { stdio: 'inherit' });
    if (pushResult.exitCode !== 0) {
      log.error(`docker push exited with code ${pushResult.exitCode}`);
      log.hint(
        'Common fixes: `docker login <registry>`, or use a fully-qualified tag (`docker.io/you/image:tag`).',
      );
      process.exit(pushResult.exitCode);
    }
    log.success(`pushed ${tag}`);
  } else {
    log.hint(`Run \`docker push ${tag}\` (or pass --push to do it now).`);
  }
};
