import { promises as fs } from 'node:fs';
import path from 'node:path';
import { loadConfig } from '../config-loader.js';
import { buildServer } from '../commands/build.js';
import { exec, isCommandAvailable } from '../utils/exec.js';
import { fileExists } from '../utils/fs.js';
import { getString, type ParsedArgs } from '../args.js';
import { log } from '../logger.js';

const DOCKERFILE_NAME = 'Dockerfile.mcify';
const FLY_TOML_NAME = 'fly.toml';

const generateDockerfile = (entryFile: string, port: number): string =>
  [
    `# Generated by \`mcify deploy fly\`. Multi-stage so the final image is small.`,
    ``,
    `FROM node:20-alpine AS deps`,
    `WORKDIR /app`,
    `COPY package.json package-lock.json* pnpm-lock.yaml* yarn.lock* ./`,
    `RUN if [ -f pnpm-lock.yaml ]; then \\`,
    `      corepack enable pnpm && pnpm install --prod --frozen-lockfile; \\`,
    `    elif [ -f yarn.lock ]; then \\`,
    `      corepack enable yarn && yarn install --production --frozen-lockfile; \\`,
    `    else \\`,
    `      npm ci --omit=dev; \\`,
    `    fi`,
    ``,
    `FROM node:20-alpine`,
    `WORKDIR /app`,
    `USER node`,
    `COPY --chown=node:node --from=deps /app/node_modules ./node_modules`,
    `COPY --chown=node:node ${entryFile} ./${entryFile}`,
    `COPY --chown=node:node package.json ./package.json`,
    ``,
    `ENV NODE_ENV=production`,
    `ENV PORT=${port}`,
    `EXPOSE ${port}`,
    ``,
    `CMD ["node", "${entryFile}"]`,
    ``,
  ].join('\n');

const generateFlyToml = (opts: { app: string; region: string; port: number }): string =>
  [
    `# Generated by \`mcify deploy fly\`. Edit and re-run to redeploy.`,
    `# https://fly.io/docs/reference/configuration/`,
    ``,
    `app = "${opts.app}"`,
    `primary_region = "${opts.region}"`,
    ``,
    `[build]`,
    `  dockerfile = "${DOCKERFILE_NAME}"`,
    ``,
    `[http_service]`,
    `  internal_port = ${opts.port}`,
    `  force_https = true`,
    `  auto_stop_machines = "stop"`,
    `  auto_start_machines = true`,
    `  min_machines_running = 0`,
    `  processes = ["app"]`,
    ``,
    `  [http_service.concurrency]`,
    `    type = "requests"`,
    `    hard_limit = 250`,
    `    soft_limit = 200`,
    ``,
    `[[vm]]`,
    `  cpu_kind = "shared"`,
    `  cpus = 1`,
    `  memory_mb = 256`,
    ``,
    `# Set secrets out-of-band:`,
    `#   fly secrets set MCIFY_AUTH_TOKEN=...`,
    `# Plain (non-secret) env can live here:`,
    `# [env]`,
    `#   PUBLIC_SOMETHING = "value"`,
    ``,
  ].join('\n');

export const runDeployFly = async (args: ParsedArgs): Promise<void> => {
  const configFlag = getString(args, 'config');
  const configPath = path.resolve(process.cwd(), configFlag ?? 'mcify.config.ts');
  const region = getString(args, 'region') ?? 'scl'; // Santiago, CL — closest to Lelemon
  const portFlag = getString(args, 'port');
  const port = portFlag ? Number.parseInt(portFlag, 10) : 8888;
  const dryRun = args.flags['dry-run'] === true;
  const launch = args.flags['launch'] === true;

  if (!(await fileExists(configPath))) {
    log.error(`Config not found: ${configPath}`);
    log.hint('Run `mcify init` to scaffold a starter project.');
    process.exit(1);
  }

  const config = await loadConfig(configPath);
  const app = getString(args, 'app') ?? config.name;
  log.hint(`server: ${config.name}@${config.version} → fly app: ${app}`);

  log.info('building Node bundle…');
  const result = await buildServer({
    configPath,
    outDir: path.resolve(process.cwd(), 'dist'),
    target: 'node',
    bundleDeps: false,
  });
  const entryRel = path.relative(process.cwd(), result.outFile).replaceAll('\\', '/');
  log.success(`bundle: ${entryRel} (${result.durationMs}ms)`);

  // Don't overwrite a manual Dockerfile.mcify — the user may have customized it.
  const dockerfilePath = path.resolve(process.cwd(), DOCKERFILE_NAME);
  if (!(await fileExists(dockerfilePath))) {
    await fs.writeFile(dockerfilePath, generateDockerfile(entryRel, port), 'utf-8');
    log.hint(`${DOCKERFILE_NAME} → generated`);
  } else {
    log.hint(`${DOCKERFILE_NAME} → exists, leaving as-is`);
  }

  // fly.toml is the source of truth for app config — same hands-off rule.
  const flyTomlPath = path.resolve(process.cwd(), FLY_TOML_NAME);
  if (!(await fileExists(flyTomlPath))) {
    await fs.writeFile(flyTomlPath, generateFlyToml({ app, region, port }), 'utf-8');
    log.hint(`${FLY_TOML_NAME} → generated (app=${app}, region=${region})`);
  } else {
    log.hint(`${FLY_TOML_NAME} → exists, leaving as-is`);
  }

  if (dryRun) {
    log.info('--dry-run: skipping flyctl');
    log.hint(
      launch
        ? 'Run manually: `flyctl launch --copy-config --no-deploy`'
        : 'Run manually: `flyctl deploy`',
    );
    return;
  }

  if (!(await isCommandAvailable('flyctl')) && !(await isCommandAvailable('fly'))) {
    log.error('flyctl is not on PATH. Install with `curl -L https://fly.io/install.sh | sh`.');
    log.hint('https://fly.io/docs/hands-on/install-flyctl/');
    process.exit(1);
  }

  const cmd = (await isCommandAvailable('flyctl')) ? 'flyctl' : 'fly';

  if (launch) {
    log.info(`${cmd} launch (first-time setup, copies config, no deploy)`);
    const r = await exec(
      cmd,
      ['launch', '--copy-config', '--no-deploy', '--name', app, '--region', region],
      {
        stdio: 'inherit',
      },
    );
    if (r.exitCode !== 0) {
      log.error(`fly launch exited with code ${r.exitCode}`);
      process.exit(r.exitCode);
    }
    log.success('app created. Run `mcify deploy fly` (without --launch) to deploy.');
    log.hint('Set secrets: `flyctl secrets set MCIFY_AUTH_TOKEN=...`');
    return;
  }

  log.info(`${cmd} deploy`);
  const r = await exec(cmd, ['deploy'], { stdio: 'inherit' });
  if (r.exitCode !== 0) {
    log.error(`fly deploy exited with code ${r.exitCode}`);
    log.hint(
      'First time? Run `mcify deploy fly --launch` (or `flyctl launch`) once to create the app.',
    );
    log.hint('Auth: `flyctl auth login`. Set secrets: `flyctl secrets set MCIFY_AUTH_TOKEN=...`.');
    process.exit(r.exitCode);
  }
  log.success(`deployed ${app}`);
};
