import { promises as fs } from 'node:fs';
import path from 'node:path';
import { loadConfig } from '../config-loader.js';
import { buildServer } from '../commands/build.js';
import { exec, isCommandAvailable } from '../utils/exec.js';
import { fileExists } from '../utils/fs.js';
import { getString, type ParsedArgs } from '../args.js';
import { log } from '../logger.js';

const RAILWAY_JSON_NAME = 'railway.json';

const generateRailwayJson = (entryFile: string, port: number): string =>
  `${JSON.stringify(
    {
      $schema: 'https://railway.com/railway.schema.json',
      // Generated by `mcify deploy railway`. Edit and re-run to redeploy.
      build: {
        // Nixpacks auto-detects Node + the right package manager from the
        // lockfile. We override the install/build steps explicitly so private
        // workspaces and pnpm work without surprises.
        builder: 'NIXPACKS',
        nixpacksPlan: {
          phases: {
            setup: {
              nixPkgs: ['nodejs_20', 'pnpm-9_x'],
            },
          },
        },
      },
      deploy: {
        startCommand: `node ${entryFile}`,
        restartPolicyType: 'ON_FAILURE',
        restartPolicyMaxRetries: 3,
        healthcheckPath: '/',
        healthcheckTimeout: 30,
      },
      environments: {
        production: {
          variables: {
            PORT: String(port),
            NODE_ENV: 'production',
          },
        },
      },
    },
    null,
    2,
  )}\n`;

export const runDeployRailway = async (args: ParsedArgs): Promise<void> => {
  const configFlag = getString(args, 'config');
  const configPath = path.resolve(process.cwd(), configFlag ?? 'mcify.config.ts');
  const portFlag = getString(args, 'port');
  const port = portFlag ? Number.parseInt(portFlag, 10) : 8888;
  const dryRun = args.flags['dry-run'] === true;
  const serviceFlag = getString(args, 'service');
  const envFlag = getString(args, 'environment') ?? 'production';

  if (!(await fileExists(configPath))) {
    log.error(`Config not found: ${configPath}`);
    log.hint('Run `mcify init` to scaffold a starter project.');
    process.exit(1);
  }

  const config = await loadConfig(configPath);
  log.hint(`server: ${config.name}@${config.version} → railway environment: ${envFlag}`);

  log.info('building Node bundle…');
  const result = await buildServer({
    configPath,
    outDir: path.resolve(process.cwd(), 'dist'),
    target: 'node',
    bundleDeps: false,
  });
  const entryRel = path.relative(process.cwd(), result.outFile).replaceAll('\\', '/');
  log.success(`bundle: ${entryRel} (${result.durationMs}ms)`);

  // railway.json is the deploy contract. Don't overwrite a manual one.
  const railwayJsonPath = path.resolve(process.cwd(), RAILWAY_JSON_NAME);
  if (!(await fileExists(railwayJsonPath))) {
    await fs.writeFile(railwayJsonPath, generateRailwayJson(entryRel, port), 'utf-8');
    log.hint(`${RAILWAY_JSON_NAME} → generated`);
  } else {
    log.hint(`${RAILWAY_JSON_NAME} → exists, leaving as-is`);
  }

  if (dryRun) {
    log.info('--dry-run: skipping `railway up`');
    log.hint('Run manually: `railway up`');
    return;
  }

  if (!(await isCommandAvailable('railway'))) {
    log.error('railway CLI is not on PATH. Install with `npm i -g @railway/cli`.');
    log.hint('https://docs.railway.app/develop/cli');
    process.exit(1);
  }

  const railwayArgs = ['up', '--environment', envFlag];
  if (serviceFlag) {
    railwayArgs.push('--service', serviceFlag);
  }

  log.info(`railway ${railwayArgs.join(' ')}`);
  const r = await exec('railway', railwayArgs, { stdio: 'inherit' });
  if (r.exitCode !== 0) {
    log.error(`railway up exited with code ${r.exitCode}`);
    log.hint(
      'First time? Run `railway login` then `railway link` (or `railway init`) to associate this directory with a Railway project.',
    );
    log.hint('Set secrets via dashboard or `railway variables set MCIFY_AUTH_TOKEN=...`.');
    process.exit(r.exitCode);
  }
  log.success(`deployed to Railway environment "${envFlag}"`);
};
