import { promises as fs } from 'node:fs';
import path from 'node:path';
import { loadConfig } from '../config-loader.js';
import { buildEdgeBundle } from './bundle.js';
import { exec, isCommandAvailable } from '../utils/exec.js';
import { fileExists } from '../utils/fs.js';
import { getString, type ParsedArgs } from '../args.js';
import { log } from '../logger.js';

const generateVercelJson = (functionPath: string): string =>
  JSON.stringify(
    {
      $schema: 'https://openapi.vercel.sh/vercel.json',
      // Single rewrite: send everything to the edge function. The MCP path
      // (`/mcp`) is handled inside the function by the Hono router.
      rewrites: [{ source: '/(.*)', destination: `/${functionPath}` }],
    },
    null,
    2,
  );

const generateApiEntry = (bundlePath: string): string =>
  // The Vercel CLI looks for `api/<name>.js` (or .ts/.mjs) and detects
  // `export const config = { runtime: 'edge' }` to deploy as an Edge Function.
  // We re-export from the bundled file so the user's whole config lands as a
  // single edge function with Web-standard Request/Response.
  [
    `// Generated by \`mcify deploy vercel\`. Re-run to refresh.`,
    `export { default, config } from '${bundlePath}';`,
    ``,
  ].join('\n');

export const runDeployVercel = async (args: ParsedArgs): Promise<void> => {
  const configFlag = getString(args, 'config');
  const configPath = path.resolve(process.cwd(), configFlag ?? 'mcify.config.ts');
  const cwd = process.cwd();
  const dryRun = args.flags['dry-run'] === true;
  const prod = args.flags['prod'] === true;
  const projectFlag = getString(args, 'project');

  if (!(await fileExists(configPath))) {
    log.error(`Config not found: ${configPath}`);
    log.hint('Run `mcify init` to scaffold a starter project.');
    process.exit(1);
  }

  log.info('loading config…');
  const config = await loadConfig(configPath);
  log.hint(`server: ${config.name}@${config.version}`);

  log.info('bundling for Vercel Edge…');
  // The bundle goes under `.vercel/output/...`-style location but Vercel's
  // CLI auto-detects from `api/`. We write the bundle next to the entry so
  // a single `vercel deploy` ships it.
  const apiDir = path.join(cwd, 'api');
  await fs.mkdir(apiDir, { recursive: true });

  const bundleOutDir = path.join(cwd, 'dist/vercel');
  const bundleFile = await buildEdgeBundle({
    configPath,
    outDir: bundleOutDir,
    target: 'vercel-edge',
  });
  const bundleSize = (await fs.stat(bundleFile)).size;
  log.success(`bundle ready (${(bundleSize / 1024).toFixed(1)} KB)`);

  // Vercel Edge Functions cap at 4 MB compressed. Surface this proactively.
  if (bundleSize > 4 * 1024 * 1024) {
    log.warn(
      'bundle is larger than 4 MB — Vercel Edge may reject. Consider trimming dependencies or switching to a serverless Node function.',
    );
  }

  const apiFunctionPath = path.join(apiDir, 'mcp.mjs');
  const relativeBundle = path.relative(apiDir, bundleFile).replaceAll('\\', '/');
  await fs.writeFile(apiFunctionPath, generateApiEntry(relativeBundle), 'utf-8');
  log.hint(`api/mcp.mjs → ${path.relative(cwd, apiFunctionPath)}`);

  // Generate vercel.json if missing. Don't overwrite — the user may have
  // their own routing.
  const vercelJsonPath = path.join(cwd, 'vercel.json');
  if (!(await fileExists(vercelJsonPath))) {
    await fs.writeFile(vercelJsonPath, generateVercelJson('api/mcp'), 'utf-8');
    log.hint('vercel.json → vercel.json (created)');
  } else {
    log.hint('vercel.json → already exists, leaving as-is');
  }

  if (dryRun) {
    log.info('--dry-run: skipping `vercel deploy`');
    log.hint(`Run manually: \`vercel${prod ? ' --prod' : ''}\``);
    return;
  }

  if (!(await isCommandAvailable('npx'))) {
    log.error('npx is required to invoke vercel. Make sure Node.js is on PATH.');
    process.exit(1);
  }

  log.info(`deploying with vercel${prod ? ' --prod' : ' (preview)'}…`);
  const vercelArgs = ['vercel'];
  if (prod) vercelArgs.push('--prod');
  if (projectFlag) vercelArgs.push('--name', projectFlag);

  const result = await exec('npx', vercelArgs, { stdio: 'inherit', cwd });
  if (result.exitCode !== 0) {
    log.error(`vercel deploy exited with code ${result.exitCode}`);
    log.hint(
      'Common fixes: run `npx vercel login`, link the project once with `npx vercel link`, or set VERCEL_TOKEN.',
    );
    process.exit(result.exitCode);
  }
  log.success('deployed to Vercel');
};
